reduced font size of Facebook btn
nognooitmeegemaakt/website pull request #8
Opened 2017-01-08 21:00 UTC by jessevdp

Text inside Facebook button was still displaying weirdly on some pages.

Reducing its font size (again) fixes it.

Fixes issue #5 (again)

2017-01-09 09:36 UTC, lesander commented
This is a rather dirty hack. I'd rather have a different `em` size for each viewport.

2017-01-09 10:32 UTC, jessevdp commented
That's not how it used to be but probably a best practise. I'll look into it.

2017-01-09 11:00 UTC, jessevdp commented
Think it's all ready to merge now. Take a look at the `font-size` yourself to see if you want to make any changes.

2017-01-16 21:14 UTC, lesander requested changes

2017-01-16 21:14 UTC, lesander commented on _sass/scale.scss
> +    font-size: 1rem !important;
Are all those `!important`s required? If I'm correct, just the media queries will override the `font-size`.

2017-01-16 21:18 UTC, jessevdp commented on _sass/scale.scss
> +    font-size: 1rem !important;
I suppose they're not needed anymore, while working on it I hadn't deleted the old styles yet... But I guess a simple test should tell us the answer...

2017-01-21 13:54 UTC, jessevdp commented
Ah, the media query **is being overwritten** as you can see in the following screenshot. I'll delete the css that overwrites it as well as the `!important` tags.

(this only happens on the news page)

<img width="333" alt="screen shot 2017-01-21 at 14 51 14" src="https://cloud.githubusercontent.com/assets/15139826/22174870/54b37882-dfe9-11e6-9acf-fba9b106fce6.png">

2017-01-21 13:55 UTC, jessevdp commented on _sass/scale.scss
> +    font-size: 1rem !important;
Ah, the media query **is being overwritten** as you can see in the following screenshot. I'll delete the css that overwrites it as well as the `!important` tags.

(this only happens on the news page)

<img width="333" alt="screen shot 2017-01-21 at 14 51 14" src="https://cloud.githubusercontent.com/assets/15139826/22174870/54b37882-dfe9-11e6-9acf-fba9b106fce6.png">

2017-01-21 13:57 UTC, jessevdp commented on _sass/scale.scss
> +    font-size: 1rem !important;
Wait a minute, can't really delete the css since it does not ***only*** affect the fb button but all links on the page.

2017-01-23 15:36 UTC, lesander commented on _sass/scale.scss
> +    font-size: 1rem !important;
Create a new css selector then?

2017-02-26 11:13 UTC, lesander approved these changes

2017-02-26 11:13 UTC, merged